name: Publish Docker image with version tag to GitHub Container Registry
on: 
  push:
    tags:
      - v1.*

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2                  
      # https://github.community/t/how-to-get-just-the-tag-name/16241/7
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image      
        env:
          SOURCE_TAG: ${{ steps.get_tag.outputs.SOURCE_TAG }}
        with:
          image: covid-bot    
          target: base
          tags: v1, ${{ env.SOURCE_TAG }}, latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
